version: "3"
services:
  derperer:
    image: ghcr.io/koyangyang/derperer:latest
    container_name: derperer
    command:
      - server
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./derperer.yaml:/root/.derperer/derperer.yaml # or use config file
    restart: always